services:
  - type: web
    name: actas-nacimiento-api
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://rolpay:nRudxktTIGGYRN7900WE38nNL97VonPI@dpg-d9hvm6fabvsc73a63tf0-a.oregon-postgres.render.com/rolpay
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '["https://actas-nacimiento-api.onrender.com"]'
