from app.schemas.acta import *
from app.schemas.registrador import *
from app.schemas.presentado import *
from app.schemas.certificado_medico import *
from app.schemas.madre import *
from app.schemas.padre import *
from app.schemas.declarante import *
from app.schemas.testigo import *
from app.schemas.nota_marginal import *
from app.schemas.familiar import *
